using System;
using System.Collections.Generic;
using System.Linq;
using HemaLeagueManager.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HemaLeagueManager.Services
{
    /// <summary>
    /// Generates a themed PDF report (standings, tournaments, club statistics)
    /// for the active league. Uses QuestPDF for layout.
    /// </summary>
    public static class PdfReportService
    {
        private const string Parchment      = "#FBF4E2";
        private const string ParchmentDark  = "#F0E6CC";
        private const string InkBrown       = "#2A1F18";
        private const string InkBrownMuted  = "#6F5E48";
        private const string Gold           = "#B58A3C";
        private const string GoldDark       = "#8A6727";

        static PdfReportService()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public static void Generate(League league, string outputPath)
        {
            var standings = ScoringSystem.CalculateStandings(league)
                .OrderByDescending(kv => kv.Value)
                .ToList();
            var clubStats = ClubStatsService.Compute(ClubRegistry.All, league)
                .OrderByDescending(s => s.AveragePoints)
                .ThenByDescending(s => s.TotalPoints)
                .ToList();

            Document.Create(doc =>
            {
                doc.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Parchment);
                    page.DefaultTextStyle(t => t.FontFamily("Segoe UI").FontSize(10).FontColor(InkBrown));

                    page.Header().Element(c => ComposeHeader(c, league));
                    page.Content().Element(c => ComposeBody(c, league, standings, clubStats));
                    page.Footer().Element(ComposeFooter);
                });
            })
            .GeneratePdf(outputPath);
        }

        // ---- Header ----
        private static void ComposeHeader(IContainer container, League league)
        {
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(left =>
                    {
                        left.Item().Text("⚔  HEMA League Manager")
                            .FontFamily("Garamond").FontSize(20).Bold().FontColor(GoldDark);
                        left.Item().Text(string.IsNullOrWhiteSpace(league.Name) ? "Untitled league" : league.Name)
                            .FontFamily("Garamond").FontSize(14).FontColor(InkBrown);
                    });

                    row.ConstantItem(170).AlignRight().Column(right =>
                    {
                        right.Item().AlignRight().Text("Season Report")
                            .FontSize(10).FontColor(InkBrownMuted);
                        right.Item().AlignRight().Text(DateTime.Now.ToString("dddd, MMMM d, yyyy"))
                            .FontSize(10).FontColor(InkBrownMuted);
                        right.Item().AlignRight().Text(league.IsClosed ? "Status: Closed" : "Status: Open")
                            .FontSize(10).FontColor(league.IsClosed ? GoldDark : InkBrownMuted);
                    });
                });

                col.Item().PaddingTop(6).LineHorizontal(2).LineColor(Gold);
            });
        }

        // ---- Footer ----
        private static void ComposeFooter(IContainer container)
        {
            container.Row(row =>
            {
                row.RelativeItem().Text("Generated by HEMA League Manager")
                    .FontSize(9).FontColor(InkBrownMuted);
                row.ConstantItem(120).AlignRight().Text(t =>
                {
                    t.DefaultTextStyle(s => s.FontSize(9).FontColor(InkBrownMuted));
                    t.Span("Page ");
                    t.CurrentPageNumber();
                    t.Span(" / ");
                    t.TotalPages();
                });
            });
        }

        // ---- Body ----
        private static void ComposeBody(
            IContainer container,
            League league,
            List<KeyValuePair<string, int>> standings,
            List<ClubStats> clubStats)
        {
            container.PaddingVertical(12).Column(col =>
            {
                col.Spacing(18);

                col.Item().Element(c => ComposeSummary(c, league, standings, clubStats));
                col.Item().Element(c => ComposeStandings(c, league, standings));
                col.Item().Element(c => ComposeClubStats(c, clubStats));
                col.Item().Element(c => ComposeTournaments(c, league));
            });
        }

        // ---- Summary card ----
        private static void ComposeSummary(
            IContainer container, League league,
            List<KeyValuePair<string, int>> standings,
            List<ClubStats> clubStats)
        {
            container.Background(ParchmentDark).Padding(12).Column(col =>
            {
                col.Item().Text("League Overview")
                    .FontFamily("Garamond").FontSize(14).Bold().FontColor(GoldDark);
                col.Item().PaddingTop(6).Row(row =>
                {
                    row.RelativeItem().Element(c => Stat(c, "Fencers", league.Fencers.Count.ToString()));
                    row.RelativeItem().Element(c => Stat(c, "Tournaments", league.Tournaments.Count.ToString()));
                    row.RelativeItem().Element(c => Stat(c, "Grand Prix", league.Tournaments.Count(t => t.IsGrandPrix).ToString()));
                    row.RelativeItem().Element(c => Stat(c, "Clubs", clubStats.Count.ToString()));
                    row.RelativeItem().Element(c => Stat(c, "Leader",
                        standings.Count > 0 ? $"{standings[0].Key} ({standings[0].Value})" : "—"));
                });
            });
        }

        private static void Stat(IContainer container, string label, string value)
        {
            container.Column(col =>
            {
                col.Item().Text(label.ToUpper()).FontSize(8).FontColor(InkBrownMuted).LetterSpacing(0.06f);
                col.Item().PaddingTop(2).Text(value).FontFamily("Garamond").FontSize(13).Bold().FontColor(InkBrown);
            });
        }

        // ---- Standings ----
        private static void ComposeStandings(
            IContainer container, League league, List<KeyValuePair<string, int>> standings)
        {
            container.Column(col =>
            {
                col.Item().Element(c => SectionTitle(c, "League Standings"));
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c =>
                    {
                        c.ConstantColumn(40);
                        c.RelativeColumn(3);
                        c.RelativeColumn(2);
                        c.ConstantColumn(45);
                        c.ConstantColumn(55);
                    });

                    table.Header(h =>
                    {
                        h.Cell().Element(c => HeaderCell(c, "#"));
                        h.Cell().Element(c => HeaderCell(c, "Fencer"));
                        h.Cell().Element(c => HeaderCell(c, "Club"));
                        h.Cell().Element(c => HeaderCell(c, "Sex"));
                        h.Cell().Element(c => HeaderCell(c, "Points", HorizontalAlignment.Right));
                    });

                    int rank = 1;
                    foreach (var (name, pts) in standings)
                    {
                        var f = league.Fencers.FirstOrDefault(x => x.Name == name);
                        var rowColor = rank % 2 == 0 ? ParchmentDark : Parchment;
                        var medal = rank switch { 1 => "🥇", 2 => "🥈", 3 => "🥉", _ => "" };
                        var rankText = string.IsNullOrEmpty(medal) ? rank.ToString() : $"{medal} {rank}";
                        var emphasize = rank <= 3;

                        var rk = rank; var em = emphasize; var rc = rowColor;
                        table.Cell().Element(c => BodyCell(c, rankText, rc, em));
                        table.Cell().Element(c => BodyCell(c, name, rc, em));
                        table.Cell().Element(c => BodyCell(c, ClubRegistry.GetShortName(f?.ClubName ?? ""), rc, em));
                        table.Cell().Element(c => BodyCell(c, f?.Sex ?? "", rc, em));
                        table.Cell().Element(c => BodyCell(c, pts.ToString(), rc, em, HorizontalAlignment.Right));
                        rank++;
                    }
                });
            });
        }

        // ---- Club stats ----
        private static void ComposeClubStats(IContainer container, List<ClubStats> stats)
        {
            if (stats.Count == 0) return;

            container.Column(col =>
            {
                col.Item().Element(c => SectionTitle(c, "Club Performance"));
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c =>
                    {
                        c.ConstantColumn(70);
                        c.RelativeColumn(3);
                        c.RelativeColumn(2);
                        c.ConstantColumn(50);
                        c.ConstantColumn(55);
                        c.ConstantColumn(55);
                        c.RelativeColumn(2);
                    });

                    table.Header(h =>
                    {
                        h.Cell().Element(c => HeaderCell(c, "Short"));
                        h.Cell().Element(c => HeaderCell(c, "Club"));
                        h.Cell().Element(c => HeaderCell(c, "City"));
                        h.Cell().Element(c => HeaderCell(c, "Fencers", HorizontalAlignment.Right));
                        h.Cell().Element(c => HeaderCell(c, "Total",   HorizontalAlignment.Right));
                        h.Cell().Element(c => HeaderCell(c, "Avg",     HorizontalAlignment.Right));
                        h.Cell().Element(c => HeaderCell(c, "Top Fencer"));
                    });

                    int i = 0;
                    foreach (var s in stats)
                    {
                        var rowColor = (i++ % 2 == 0) ? Parchment : ParchmentDark;
                        var rc = rowColor;
                        table.Cell().Element(c => BodyCell(c, ClubRegistry.GetShortName(s.ClubName), rc));
                        table.Cell().Element(c => BodyCell(c, s.ClubName, rc));
                        table.Cell().Element(c => BodyCell(c, s.City, rc));
                        table.Cell().Element(c => BodyCell(c, s.FencerCount.ToString(), rc, false, HorizontalAlignment.Right));
                        table.Cell().Element(c => BodyCell(c, s.TotalPoints.ToString(), rc, false, HorizontalAlignment.Right));
                        table.Cell().Element(c => BodyCell(c, s.AveragePoints.ToString("0.0"), rc, false, HorizontalAlignment.Right));
                        table.Cell().Element(c => BodyCell(c,
                            string.IsNullOrEmpty(s.BestFencerName) ? "—" : $"{s.BestFencerName} ({s.BestFencerPoints})",
                            rc));
                    }
                });
            });
        }

        // ---- Tournaments ----
        private static void ComposeTournaments(IContainer container, League league)
        {
            if (league.Tournaments.Count == 0) return;

            container.Column(col =>
            {
                col.Item().Element(c => SectionTitle(c, "Tournaments"));

                foreach (var t in league.Tournaments.OrderBy(t => t.Date))
                {
                    col.Item().PaddingTop(4).Background(ParchmentDark).Padding(8).Column(card =>
                    {
                        card.Item().Row(r =>
                        {
                            r.RelativeItem().Text(text =>
                            {
                                text.Span(t.IsGrandPrix ? "★ " : "").FontColor(GoldDark).Bold();
                                text.Span(t.Name).FontFamily("Garamond").FontSize(13).Bold().FontColor(InkBrown);
                            });
                            r.ConstantItem(180).AlignRight().Text(t.Date.ToString("dddd, MMMM d, yyyy"))
                                .FontSize(9).FontColor(InkBrownMuted);
                        });

                        if (t.IsGrandPrix)
                            card.Item().Text("Grand Prix  •  points doubled")
                                .FontSize(9).FontColor(GoldDark).Italic();

                        if (t.Placements.Count > 0)
                        {
                            card.Item().PaddingTop(4).Table(table =>
                            {
                                table.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(40);
                                    c.RelativeColumn(3);
                                    c.RelativeColumn(2);
                                    c.ConstantColumn(50);
                                });

                                table.Header(h =>
                                {
                                    h.Cell().Element(c => HeaderCell(c, "#"));
                                    h.Cell().Element(c => HeaderCell(c, "Fencer"));
                                    h.Cell().Element(c => HeaderCell(c, "Club"));
                                    h.Cell().Element(c => HeaderCell(c, "Pts", HorizontalAlignment.Right));
                                });

                                int take = Math.Min(5, t.Placements.Count);
                                for (int i = 0; i < take; i++)
                                {
                                    var idx = i;
                                    var name = t.Placements[idx];
                                    var f = league.Fencers.FirstOrDefault(x => x.Name == name);
                                    var pts = ScoringSystem.GetPointsForPlacement(idx, t);
                                    var rowColor = idx % 2 == 0 ? Parchment : ParchmentDark;
                                    var emphasize = idx < 3;
                                    var rc = rowColor; var em = emphasize;

                                    table.Cell().Element(c => BodyCell(c, (idx + 1).ToString(), rc, em));
                                    table.Cell().Element(c => BodyCell(c, name, rc, em));
                                    table.Cell().Element(c => BodyCell(c, ClubRegistry.GetShortName(f?.ClubName ?? ""), rc, em));
                                    table.Cell().Element(c => BodyCell(c, pts.ToString(), rc, em, HorizontalAlignment.Right));
                                }

                                if (t.Placements.Count > 5)
                                {
                                    table.Cell().ColumnSpan(4).Background(Parchment).Padding(3)
                                        .Text($"…and {t.Placements.Count - 5} more placements")
                                        .FontSize(8).Italic().FontColor(InkBrownMuted);
                                }
                            });
                        }
                    });
                }
            });
        }

        // ---- Shared cell helpers (all take IContainer) ----
        private static void SectionTitle(IContainer container, string text)
        {
            container.Column(col =>
            {
                col.Item().Text(text).FontFamily("Garamond").FontSize(16).Bold().FontColor(GoldDark);
                col.Item().PaddingTop(2).LineHorizontal(1).LineColor(Gold);
                col.Item().PaddingBottom(4);
            });
        }

        private static void HeaderCell(IContainer cell, string text,
            HorizontalAlignment align = HorizontalAlignment.Left)
        {
            cell.Background(GoldDark).Padding(5)
                .AlignmentFor(align)
                .Text(text).FontSize(9).Bold().FontColor(Parchment).LetterSpacing(0.04f);
        }

        private static void BodyCell(IContainer cell, string text,
            string background, bool emphasize = false,
            HorizontalAlignment align = HorizontalAlignment.Left)
        {
            var c = cell.Background(background).Padding(4).AlignmentFor(align);
            var span = c.Text(text ?? "")
                .FontSize(10)
                .FontColor(emphasize ? GoldDark : InkBrown);
            if (emphasize) span.Bold();
        }

        private enum HorizontalAlignment { Left, Right, Center }

        private static IContainer AlignmentFor(this IContainer container, HorizontalAlignment a) => a switch
        {
            HorizontalAlignment.Right  => container.AlignRight(),
            HorizontalAlignment.Center => container.AlignCenter(),
            _ => container.AlignLeft()
        };
    }
}